name = "NMRSpecifyRegions"
uuid = "2c6f6ba7-1a3c-4d31-8511-d336c09a6ae6"
authors = ["Roy <rwang013@uottawa.ca> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
